name: convert_md_pdf

on: [push]

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: docker://pandoc/latex:2.9
        with:
          args: "-f markdown -t pdf -o README.pdf README.md" # gets appended to pandoc command
      - uses: actions/upload-artifact@v2
        with:
          name: README.pdf
          path: pdf
